# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-28 09:12
from __future__ import unicode_literals

import cached_fields.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('total_changed', models.DateTimeField(null=True)),
            ],
            bases=(cached_fields.mixins.CachedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='prefetchapp.OrderSummary')),
            ],
        ),
    ]
