# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 11:33
from __future__ import unicode_literals

import cached_fields.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('total_last_updated', models.DateTimeField(null=True)),
            ],
            bases=(cached_fields.mixins.CachedFieldsMixin, models.Model),
        ),
    ]
