# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-27 01:21
from __future__ import unicode_literals

import cached_fields.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('total_changed', models.DateTimeField(null=True)),
            ],
            bases=(cached_fields.mixins.CachedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handledapp.Item'),
        ),
    ]
