# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-28 04:38
from __future__ import unicode_literals

import cached_fields.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handledapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_one', models.IntegerField()),
                ('value_two', models.IntegerField()),
                ('multiple', models.IntegerField()),
                ('multiple_changed', models.DateTimeField(null=True)),
                ('addition', models.IntegerField()),
                ('addition_changed', models.DateTimeField(null=True)),
            ],
            bases=(cached_fields.mixins.CachedFieldsMixin, models.Model),
        ),
    ]
