# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handledapp', '0002_carrot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='handledapp.Item'),
        ),
    ]
